### ISSUE TITLE
hello world app just opens blank file

### ISSUE THREAD

**Issue by andremw** [mangini/chrome-apis-sublime#7]
when I go to Chrome -> New App -> Hello world, instead of creating those 3 files it just creates a new untitled tab.. and console shows the following message:

"Traceback (most recent call last):
  File ".\sublime_plugin.py", line 337, in run_
  File ".\ChromeApi_Commands.py", line 27, in run
  File ".\ChromeApi_Commands.py", line 8, in get_samplename_from_file
Exception: Invalid sample file: C:\Users\Andre\AppData\Roaming\Sublime Text 2\Packages\Chrome Apps and Extensions\snippets\sampleapp_helloworld\index_html.sublime-snippet"

**Comment by mangini** [comment]
Fixed. Package Control should update your installed version in the next hours. Thanks for reporting!

**Comment by andremw** [comment]
Now it's opening the three tabs with correct names, but they're all blank. :/

Edit: Now I realized that I forgot the error logs.. Sorry. I'm gonna write it here tonight.

Edit2: console just prints "HERE!" three times.

**Comment by mangini** [comment]
Damn, it is fixed now, and I've searched (and fixed) for other possible windows path bugs all around the code. I still don't have a Win machine to test, so I count on you to tell me if it works :-)  (but this time I did a better job). Thanks!  (will leave the bug open until you verify)

**Comment by andremw** [comment]
It just opens one blank file, index.html, and the console prints the following:

[ChromeApp] deactivated for view None
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 337, in run_
  File ".\ChromeApi_Commands.py", line 29, in run
  File ".\re.py", line 151, in sub
  File ".\re.py", line 245, in _compile
sre_constants.error: unbalanced parenthesis

**Comment by mangini** [comment]
Ouch, this is embarrassing :-(  I grabbed a Windows virtual machine today and quickly tested it this latest fix. I'm really sorry about that. It seems that Sublime treats forward slash instead of backslash in the insert_snippet command, even in backslash platforms like Windows. Thank you very much for your patience!

**Comment by andremw** [comment]
I would also say thank you for your patience.. haha
And... now it's working. Good job!
It's my pleasure to help!

**Comment by baravak** [comment]
tnx and
disable Chrome> New app> Hello world in sublime text 3
and i dont have any DOC for This package
